[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_mysql", "php84Extensions.mysqli", "php84Extensions.zip", "php84Extensions.mbstring", "composer"]

[phases.install]
cmds = ["cd backend && composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["cd backend && php bin/console cache:clear --env=prod"]

[start]
cmd = "./start.sh"
