[phases.setup]
nixPkgs = ["php", "composer"]

[phases.install]
cmds = [
  "cd backend && composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "cd backend && php -S 0.0.0.0:$PORT -t public"
