nelmio_cors:
    defaults:
        allow_origin: ['https://kanban-production-302f.up.railway.app/']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
